package practica5_diu;

import java.awt.event.ItemEvent;

public class Colores extends javax.swing.JFrame {

    boolean rojo, verde, azul;
    public Colores() {
        initComponents(); 
        rojo = true;
        verde = true;
        azul = true;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPosiciones = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbTodos = new javax.swing.JCheckBox();
        cbRojo = new javax.swing.JCheckBox();
        cbVerde = new javax.swing.JCheckBox();
        cbAzul = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        supIzq = new javax.swing.JRadioButton();
        supDer = new javax.swing.JRadioButton();
        infIzq = new javax.swing.JRadioButton();
        infDer = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        lienzo = new practica5_diu.Lienzo();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Canales de color");

        cbTodos.setSelected(true);
        cbTodos.setText("Todos");
        cbTodos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTodosItemStateChanged(evt);
            }
        });

        cbRojo.setSelected(true);
        cbRojo.setText("Rojo");
        cbRojo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRojoItemStateChanged(evt);
            }
        });
        cbRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRojoActionPerformed(evt);
            }
        });

        cbVerde.setSelected(true);
        cbVerde.setText("Verde");
        cbVerde.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbVerdeItemStateChanged(evt);
            }
        });

        cbAzul.setSelected(true);
        cbAzul.setText("Azul");
        cbAzul.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAzulItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTodos)
                    .addComponent(cbRojo)
                    .addComponent(cbVerde)
                    .addComponent(cbAzul))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbRojo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbVerde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbAzul)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        grupoPosiciones.add(supIzq);
        supIzq.setText("Esquina superior izquierda");
        supIzq.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                supIzqItemStateChanged(evt);
            }
        });

        grupoPosiciones.add(supDer);
        supDer.setText("Esquina superior derecha");
        supDer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                supDerItemStateChanged(evt);
            }
        });
        supDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supDerActionPerformed(evt);
            }
        });

        grupoPosiciones.add(infIzq);
        infIzq.setText("Esquina inferior izquierda");
        infIzq.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                infIzqItemStateChanged(evt);
            }
        });
        infIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infIzqActionPerformed(evt);
            }
        });

        grupoPosiciones.add(infDer);
        infDer.setText("Esquina inferior derecha");
        infDer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                infDerItemStateChanged(evt);
            }
        });

        jLabel2.setText("Posición logo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supIzq)
                    .addComponent(infIzq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supDer)
                    .addComponent(infDer))
                .addGap(35, 35, 35))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supIzq)
                    .addComponent(supDer))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infIzq)
                    .addComponent(infDer))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infIzqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infIzqActionPerformed

    private void cbTodosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTodosItemStateChanged
        int estado = evt.getStateChange();        
               
        if(estado == ItemEvent.SELECTED){
            cbRojo.setSelected(true);
            rojo = true;
            
            cbVerde.setSelected(true);
            verde = true;
            
            cbAzul.setSelected(true);
            azul = true; 
        }        

        lienzo.setColores(rojo,verde,azul);
    }//GEN-LAST:event_cbTodosItemStateChanged

    private void cbRojoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRojoItemStateChanged
        int estado = evt.getStateChange();
        
        if(estado == ItemEvent.SELECTED){
            rojo = true;
        }
        
        if(estado == ItemEvent.DESELECTED){            
            if(verde == false && azul == false){
                cbRojo.setSelected(true);
            }else{
                rojo = false;
                cbTodos.setSelected(false);  
            }            
        }
        
        if(rojo == true && azul == true && verde == true){
            cbTodos.setSelected(true);
        }
        
        
        
        lienzo.setColores(rojo,verde,azul);
    }//GEN-LAST:event_cbRojoItemStateChanged

    private void cbVerdeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbVerdeItemStateChanged
        int estado = evt.getStateChange();
        
        if(estado == ItemEvent.SELECTED){
            verde = true;
        }
        
        if(estado == ItemEvent.DESELECTED){            
            if(rojo == false && azul == false){
                cbVerde.setSelected(true);
            }else{
                verde = false;
                cbTodos.setSelected(false); 
            }         
        }
        
        if(rojo == true && azul == true && verde == true){
            cbTodos.setSelected(true);
        }
        
        lienzo.setColores(rojo,verde,azul);
    }//GEN-LAST:event_cbVerdeItemStateChanged

    private void cbAzulItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAzulItemStateChanged
        int estado = evt.getStateChange();
        
        if(estado == ItemEvent.SELECTED){
            azul = true;
        }
        
        if(estado == ItemEvent.DESELECTED){
            if(rojo == false && verde == false){
                cbAzul.setSelected(true);
            }else{
                azul = false;
                cbTodos.setSelected(false);
            }            
        }
        
        if(rojo == true && azul == true && verde == true){
            cbTodos.setSelected(true);
        }
        
        lienzo.setColores(rojo,verde,azul);
    }//GEN-LAST:event_cbAzulItemStateChanged

    private void cbRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRojoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRojoActionPerformed

    private void supDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supDerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supDerActionPerformed

    private void supDerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_supDerItemStateChanged
        lienzo.setPosicion(2);
    }//GEN-LAST:event_supDerItemStateChanged

    private void supIzqItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_supIzqItemStateChanged
        lienzo.setPosicion(0);
    }//GEN-LAST:event_supIzqItemStateChanged

    private void infIzqItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_infIzqItemStateChanged
        lienzo.setPosicion(1);
    }//GEN-LAST:event_infIzqItemStateChanged

    private void infDerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_infDerItemStateChanged
        lienzo.setPosicion(3);
    }//GEN-LAST:event_infDerItemStateChanged

       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbAzul;
    private javax.swing.JCheckBox cbRojo;
    private javax.swing.JCheckBox cbTodos;
    private javax.swing.JCheckBox cbVerde;
    private javax.swing.ButtonGroup grupoPosiciones;
    private javax.swing.JRadioButton infDer;
    private javax.swing.JRadioButton infIzq;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private practica5_diu.Lienzo lienzo;
    private javax.swing.JRadioButton supDer;
    private javax.swing.JRadioButton supIzq;
    // End of variables declaration//GEN-END:variables
}
